<header>
    <div class="container">
        <div class="row">
            <div class="col-sm-3">
                <a href="/">
                    <img src="https://cdn.graze.com/static/19-1506075161/images/graze/en/press-pack/graze-logo-transparent.png" class="img-responsive">
                </a>
            </div>
            ddd
            <div class="col-sm-9">
                <a class="nav__item link-nowrap pull-right" href="/basket">
                    <i class="fa fa-shopping-cart"></i>
                    <span data-cart-quantity=""><?= $summary['count']?></span>
                    <span data-cart-descriptor=""> items: </span>
                    <span data-cart-price=""><span class="price">£ <?= $summary['total']?></span></span>
                </a>
            </div>
        </div>
    </div>
</header>
