<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>graze shop</title>
    <link href="https://pistachio-cdn.graze.com/dev/css/pistachio.css" rel="stylesheet">
    <style>
    body {
        padding-top: 3em;
    }
    .panel__header {
        background-color: #fff
    }
    .panel__body {
        padding: 0;
    }
    .panel__footer a {
        float: right;
        margin-top: -.5em;
    }
    </style>
    <script src="https://use.fontawesome.com/664e56f6d4.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
    <?= $this->fetch('header.phtml') ?>

    <div class="container">
           <?= $content ?>
    </div>

    <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
    <script src="https://pistachio-cdn.graze.com/dev/js/pistachio.js"></script>
</body>
</html>
