<h1>Welcome to graze!</h1>

<ul class="grid">
    <? foreach ($items as $item): ?>

        <li class="grid__col-xs-6 grid__col-sm-4 grid__col-md-3 grid__panel grid__panel--list-xxs">
            <div class="panel">
                <div class="panel__header">
                    <?= $item->name ?>
                </div>
                <div class="panel__body">
                    <p>
                        <img src="<?= $item->image_url ?>">
                    </p>
                </div>
                <div class="panel__footer">
                    <p>
                        £<?= $item->price ?>
                        <a href="/basket/add/<?= $item->id ?>" class="button button--primary">add to basket</a>
                    </p>
                </div>
            </div>
        </li>

    <? endforeach ?>
</ul>


